import { ListaPreguntas } from "./lista-preguntas";

export const LISTAPREGUNTAS :ListaPreguntas[]=[
    {preguntas:'¿Cómo se define TypeScript?',respuesta:'TypeScript es un lenguaje de programación de código abierto desarrollado por Microsoft que se basa en JavaScript. Se define como un superset de JavaScript, lo que significa que TypeScript extiende y mejora las capacidades de JavaScript al tiempo que mantiene su compatibilidad con este último. '},
    {preguntas:'¿Cuál es la principal diferencia de TypeScript respecto de JavaScript?',respuesta:'La principal diferencia entre TypeScript y JavaScript es la adición de un sistema de tipado estático en TypeScript. Mientras que JavaScript es un lenguaje de programación de tipado dinámico, lo que significa que las variables no tienen tipos de datos fijos y pueden cambiar durante la ejecución, TypeScript introduce la definición de tipos de datos en tiempo de desarrollo. '},
    {preguntas:'Muestra la lista de tipos básicos de TypeScript.',respuesta:'number: Representa números, ya sean enteros o números de punto flotante.'+
    'string: Representa cadenas de caracteres'
    +'boolean: Representa valores booleanos, es decir, true o false.null: Representa un valor nulo.undefined: Representa un valor indefinido.object: Representa cualquier objeto no específico. Se utiliza para casos donde no se conoce el tipo exacto del objeto.symbol: Representa valores de tipo Symbol, que se utilizan para crear propiedades de objetos con nombres únicos.bigint: Representa números enteros grandes, que son mayores que el rango soportado por el tipo number.any: Representa cualquier tipo de valor. Se utiliza cuando no se quiere aplicar una verificación de tipo estática.void: Representa la ausencia de valor, generalmente se usa como el tipo de retorno de funciones que no devuelven ningún valor.'},
    {preguntas:'¿Con qué tres elementos podemos crear un tipo personalizado en TypeScript?',respuesta:'1:Interfaces 2: Tipos definidos por el usuario 3: Clases'},
    {preguntas:'¿Puedo ejecutar TypeScript en un navegador? Explica tu respuesta.',respuesta:'o puedes ejecutar directamente código TypeScript en un navegador web, ya que los navegadores solo entienden y ejecutan código JavaScript. TypeScript es un superset de JavaScript, lo que significa que se debe compilar a JavaScript antes de poder ser ejecutado en un navegador.'},
    {preguntas:'Entonces, ¿cómo es que puedo ver con las herramientas del desarrollador del navegador los archivo ts?',respuesta:'Sin embargo, puedes depurar y visualizar código TypeScript utilizando las herramientas de desarrollador del navegador a través de Source Maps. Los Source Maps son archivos que vinculan el código TypeScript original con el código JavaScript resultante, lo que facilita la depuración en TypeScript en el entorno del navegador. '},
    {preguntas:'¿Para qué sirve el archivo tsconfig.json?',respuesta:'El archivo tsconfig.json es un archivo de configuración fundamental en proyectos que utilizan TypeScript. Sirve para definir y configurar diversas opciones y ajustes relacionados con la compilación y el comportamiento del compilador de TypeScript (tsc).'}
];